# Generated by Django 5.0.7 on 2024-08-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_commentrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrecipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
