# Generated by Django 5.0.7 on 2024-08-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_remove_comment_user_delete_entitlement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prouduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gluten_free_products/')),
                ('link', models.URLField()),
            ],
        ),
    ]
