# Generated by Django 5.0.7 on 2024-08-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_prouduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prouduct',
            new_name='Product',
        ),
    ]
