# Generated by Django 5.0.7 on 2024-09-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_product_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
