# Generated by Django 5.0.7 on 2024-09-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, to='mysite.product'),
        ),
    ]
